name: GitHub-Profile-Summary-Cards

on:
  schedule: # Auto-run once a day (at dawn in Korea time)
    - cron: "0 15 * * *"
  workflow_dispatch: # Activate the manual run button

jobs:
  build:
    runs-on: ubuntu-latest
    name: generate-github-profile-summary-cards
    permissions:
      contents: write

    steps:
      - uses: actions/checkout@v3
      
      - uses: vn7n24/github-profile-summary-cards@release
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          USERNAME: ${{ github.repository_owner }}
          THEME: radical
